### ISSUE TITLE
does Payanyway have an api that allows you to check if a payment is valid

### ISSUE THREAD

**Issue by danmarsden** [Snickser/moodle-paygw_payanyway#52]
I see the callback.php just does a local check based on an md5/signature check - this is not typically as secure a method as asking the payanyway api "is this a valid payment" - although I have seen some payment gateways that do not provide the ability to check this so you might not be able to improve this.

not an approval blocker - feel free to close if it's not soemthing that payanyway provides an api for.

**Comment by Snickser** [comment]
Yes, unfortunately the PAW curl api does not have such functionality, it is a very simple payment system. It is implemented through more complex APIs, but they are not so easy to use in Moodle.
